const STORAGE_KEY='padelMatchmakerVersion7';
const LEGACY_KEY='padelMatchmakerVersion5';
let squad=[],tonightIds=[],reserveIds=[],tournamentId=null,currentRound=0,displayedRound=0,rounds=[],participantTarget=20,totalRounds=4,tournamentHistory=[],selectedProfileId=null,profileReturnView='squadView';

function uid(prefix='id'){return prefix+'-'+Date.now()+'-'+Math.random().toString(36).slice(2,10)}
function createPlayer(name){return{id:uid('player'),name,ratingPoints:500,games:0,wins:0,losses:0,matchPointsFor:0,matchPointsAgainst:0,results:[],createdAt:new Date().toISOString()}}
function init(){loadState();migratePlayers();cleanInvalidReferences();updateUI()}
function migratePlayers(){squad.forEach(p=>{if(typeof p.ratingPoints!=='number')p.ratingPoints=typeof p.points==='number'?p.points:500;if(typeof p.games!=='number')p.games=0;if(typeof p.wins!=='number')p.wins=0;if(typeof p.losses!=='number')p.losses=0;if(typeof p.matchPointsFor!=='number')p.matchPointsFor=0;if(typeof p.matchPointsAgainst!=='number')p.matchPointsAgainst=0;if(!Array.isArray(p.results))p.results=[]});if(!Number.isInteger(participantTarget)||participantTarget<4||participantTarget%4!==0)participantTarget=20;if(!Number.isInteger(totalRounds)||totalRounds<1)totalRounds=4;saveState()}
function cleanInvalidReferences(){const ids=new Set(squad.map(p=>p.id));tonightIds=tonightIds.filter(id=>ids.has(id));reserveIds=reserveIds.filter(id=>ids.has(id)&&!tonightIds.includes(id));rounds.forEach(r=>r.matches=(r.matches||[]).filter(m=>[...m.teamA,...m.teamB].every(id=>ids.has(id))));if(selectedProfileId&&!ids.has(selectedProfileId))selectedProfileId=null}
function getCourtCount(){return participantTarget/4}
function getPlayer(id){return squad.find(p=>p.id===id)}
function getTonightPlayers(){return tonightIds.map(getPlayer).filter(Boolean)}
function getTonightResults(p){return tournamentId?p.results.filter(r=>r.tournamentId===tournamentId):[]}
function getTonightStats(p){return getTonightResults(p).reduce((s,r)=>{s.games++;s.matchPointsFor+=r.scoreFor;s.matchPointsAgainst+=r.scoreAgainst;r.result==='W'?s.wins++:s.losses++;return s},{games:0,wins:0,losses:0,matchPointsFor:0,matchPointsAgainst:0})}
function getLeaderboard(){return getTonightPlayers().sort((a,b)=>{const A=getTonightStats(a),B=getTonightStats(b);if(b.ratingPoints!==a.ratingPoints)return b.ratingPoints-a.ratingPoints;if(B.matchPointsFor!==A.matchPointsFor)return B.matchPointsFor-A.matchPointsFor;const ad=A.matchPointsFor-A.matchPointsAgainst,bd=B.matchPointsFor-B.matchPointsAgainst;if(bd!==ad)return bd-ad;if(B.wins!==A.wins)return B.wins-A.wins;return tonightIds.indexOf(a.id)-tonightIds.indexOf(b.id)})}
function getCurrentRoundData(){return rounds.find(r=>r.roundNumber===currentRound)}
function getDisplayedRoundData(){return rounds.find(r=>r.roundNumber===displayedRound)}

function addPlayer(){const input=document.getElementById('newPlayerName'),name=input.value.trim();if(!name){alert('Indtast spillerens navn.');return}if(squad.some(p=>p.name.toLowerCase()===name.toLowerCase())){alert('Spilleren findes allerede.');return}const p=createPlayer(name);squad.push(p);input.value='';saveState();updateUI();openPlayerProfile(p.id,null,'squadView')}
function deletePlayer(id,event){if(event)event.stopPropagation();if(currentRound>0){alert('En spiller kan ikke slettes, mens en turnering er i gang.');return}const p=getPlayer(id);if(!p)return;if(!confirm(`Vil du permanent slette ${p.name}?${p.games?`\n\n${p.games} kampe og al statistik slettes.`:''}`))return;squad=squad.filter(x=>x.id!==id);tonightIds=tonightIds.filter(x=>x!==id);reserveIds=reserveIds.filter(x=>x!==id);selectedProfileId=null;saveState();updateUI();showView('squadView')}
function editPlayerName(){const p=getPlayer(selectedProfileId),input=document.getElementById('profileNameInput');if(!p||!input)return;const name=input.value.trim();if(!name){alert('Navnet må ikke være tomt.');return}if(squad.some(x=>x.id!==p.id&&x.name.toLowerCase()===name.toLowerCase())){alert('Navnet findes allerede.');return}p.name=name;saveState();updateUI();renderPlayerProfile()}
function changeParticipantTarget(){const el=document.getElementById('participantTarget'),value=Number(el.value);if(currentRound>0){alert('Antallet kan ikke ændres under en turnering.');el.value=participantTarget;return}if(!Number.isInteger(value)||value<4||value%4!==0){alert('Antallet skal være mindst 4 og deleligt med 4.');el.value=participantTarget;return}participantTarget=value;while(tonightIds.length>participantTarget)reserveIds.push(tonightIds.pop());saveState();updateUI()}
function changeTotalRounds(){const el=document.getElementById('totalRoundsInput'),value=Number(el.value);if(currentRound>0){alert('Antal runder kan ikke ændres efter start.');el.value=totalRounds;return}if(!Number.isInteger(value)||value<1||value>12){alert('Vælg mellem 1 og 12 runder.');el.value=totalRounds;return}totalRounds=value;saveState();updateUI()}
function cyclePlayerStatus(id){if(currentRound>0){alert('Brug Admin → Spillerskifte under en aktiv turnering.');return}if(tonightIds.includes(id)){tonightIds=tonightIds.filter(x=>x!==id);reserveIds.push(id)}else if(reserveIds.includes(id)){reserveIds=reserveIds.filter(x=>x!==id)}else{if(tonightIds.length<participantTarget)tonightIds.push(id);else reserveIds.push(id)}saveState();updateUI()}
function confirmTonightPlayers(){if(tonightIds.length!==participantTarget){alert(`Der skal vælges præcis ${participantTarget} aktive spillere.`);return}tournamentId=uid('tournament');currentRound=0;displayedRound=0;rounds=[];saveState();updateUI();showView('homeView')}

function generateNextRound(){if(tonightIds.length!==participantTarget){alert(`Vælg først ${participantTarget} aktive spillere.`);showView('squadView');return}if(!tournamentId)tournamentId=uid('tournament');if(currentRound>=totalRounds){alert('Alle runder er oprettet.');return}const prev=getCurrentRoundData();if(prev&&!allMatchesSaved(prev)){alert(`Gem alle ${getCourtCount()} resultater først.`);displayedRound=currentRound;showView('matchesView');return}const lb=getLeaderboard(),next=currentRound+1,matches=[];for(let c=0;c<getCourtCount();c++){const b=c*4;matches.push({id:uid('match'),tournamentId,round:next,court:c+1,teamA:[lb[b].id,lb[b+2].id],teamB:[lb[b+1].id,lb[b+3].id],rankA:[b+1,b+3],rankB:[b+2,b+4],scoreA:null,scoreB:null,saved:false,applied:false})}rounds.push({roundNumber:next,createdAt:new Date().toISOString(),matches});currentRound=next;displayedRound=next;saveState();updateUI();showView('matchesView')}
function saveMatch(id){const r=rounds.find(x=>x.matches.some(m=>m.id===id)),m=r&&r.matches.find(x=>x.id===id);if(!m||m.saved)return;const a=document.getElementById('scoreA-'+id).value.trim(),b=document.getElementById('scoreB-'+id).value.trim();if(a===''||b===''){alert('Indtast point for begge par.');return}const A=Number(a),B=Number(b);if(!Number.isInteger(A)||!Number.isInteger(B)||A<0||B<0||A===B){alert('Indtast et gyldigt resultat med en vinder.');return}m.scoreA=A;m.scoreB=B;m.saved=true;applyMatchResult(m);saveState();updateUI();if(allMatchesSaved(r)){if(r.roundNumber<totalRounds)setTimeout(()=>{if(confirm('Runden er færdig. Opret næste runde?'))generateNextRound()},150);else setTimeout(()=>finishTournament(),150)}}
function applyMatchResult(m){if(m.applied)return;applyResultToTeam(m,m.teamA,m.scoreA,m.scoreB,m.scoreA>m.scoreB);applyResultToTeam(m,m.teamB,m.scoreB,m.scoreA,m.scoreB>m.scoreA);m.applied=true}
function applyResultToTeam(m,ids,scoreFor,scoreAgainst,won){ids.forEach(id=>{const p=getPlayer(id);if(!p)return;p.ratingPoints+=won?50:-50;p.games++;won?p.wins++:p.losses++;p.matchPointsFor+=scoreFor;p.matchPointsAgainst+=scoreAgainst;p.results.push({id:uid('result'),matchId:m.id,tournamentId:m.tournamentId,date:new Date().toISOString(),round:m.round,court:m.court,result:won?'W':'L',scoreFor,scoreAgainst,ratingChange:won?50:-50})})}
function editMatch(id){const r=rounds.find(x=>x.matches.some(m=>m.id===id)),m=r&&r.matches.find(x=>x.id===id);if(!m||!m.saved)return;if(m.round<currentRound){alert('Resultatet er låst, fordi en senere runde er oprettet.');return}if(!confirm('Vil du rette resultatet?'))return;rollbackMatchResult(m);m.scoreA=null;m.scoreB=null;m.saved=false;m.applied=false;saveState();updateUI()}
function rollbackMatchResult(m){if(!m.applied)return;[...m.teamA,...m.teamB].forEach(id=>{const p=getPlayer(id);if(!p)return;const res=p.results.find(r=>r.matchId===m.id);if(!res)return;p.ratingPoints-=res.ratingChange;p.games=Math.max(0,p.games-1);res.result==='W'?p.wins=Math.max(0,p.wins-1):p.losses=Math.max(0,p.losses-1);p.matchPointsFor=Math.max(0,p.matchPointsFor-res.scoreFor);p.matchPointsAgainst=Math.max(0,p.matchPointsAgainst-res.scoreAgainst);p.results=p.results.filter(r=>r.matchId!==m.id)});m.applied=false}
function allMatchesSaved(r){return r&&r.matches.length===getCourtCount()&&r.matches.every(m=>m.saved)}
function finishTournament(){const exists=tournamentHistory.some(t=>t.id===tournamentId);if(!exists){const board=getLeaderboard().map((p,i)=>({place:i+1,playerId:p.id,name:p.name,ratingPoints:p.ratingPoints,stats:getTonightStats(p)}));tournamentHistory.unshift({id:tournamentId,date:new Date().toISOString(),players:participantTarget,reserves:reserveIds.map(id=>getPlayer(id)?.name).filter(Boolean),roundCount:totalRounds,courts:getCourtCount(),winner:board[0]?.name||'-',finalBoard:board,rounds:JSON.parse(JSON.stringify(rounds))});tournamentHistory=tournamentHistory.slice(0,50);saveState()}alert('Turneringen er afsluttet og gemt i historikken.');showView('leaderView')}

function substitutePlayer(){if(!tournamentId){alert('Der er ingen aktiv turnering.');return}const outId=document.getElementById('outPlayerSelect').value,inId=document.getElementById('inPlayerSelect').value;if(!outId||!inId){alert('Vælg både spiller ud og reserve ind.');return}const out=getPlayer(outId),incoming=getPlayer(inId);if(!out||!incoming)return;const current=getCurrentRoundData();if(current&&current.matches.some(m=>m.saved&&[...m.teamA,...m.teamB].includes(outId))){alert('Spilleren har allerede et gemt resultat i denne runde. Skift først efter runden.');return}if(!confirm(`${out.name} ud og ${incoming.name} ind? Reserven beholder sin egen rating.`))return;tonightIds=tonightIds.map(id=>id===outId?inId:id);reserveIds=reserveIds.filter(id=>id!==inId);reserveIds.push(outId);if(current){current.matches.forEach(m=>{m.teamA=m.teamA.map(id=>id===outId?inId:id);m.teamB=m.teamB.map(id=>id===outId?inId:id)})}saveState();updateUI();alert('Spillerskiftet er gennemført.')}

function openPlayerProfile(id,event,returnView){if(event)event.stopPropagation();selectedProfileId=id;profileReturnView=returnView||'squadView';showView('profileView')}
function closePlayerProfile(){showView(profileReturnView==='profileView'?'squadView':profileReturnView)}
function getTournamentGroups(p){const groups={};p.results.forEach(r=>{const key=r.tournamentId||'legacy';if(!groups[key])groups[key]={id:key,date:r.date,results:[]};groups[key].results.push(r)});return Object.values(groups).sort((a,b)=>new Date(b.date)-new Date(a.date))}
function buildRatingChart(p){const results=[...p.results].sort((a,b)=>new Date(a.date)-new Date(b.date));if(!results.length)return '<div class="empty-state">Ingen ratinghistorik endnu.</div>';const total=results.reduce((s,r)=>s+(r.ratingChange||0),0);let rating=p.ratingPoints-total;const values=[rating];results.forEach(r=>{rating+=r.ratingChange||0;values.push(rating)});const w=640,h=220,pad=28,min0=Math.min(...values),max0=Math.max(...values),min=min0===max0?min0-50:min0,max=max0===min0?max0+50:max0;const pts=values.map((v,i)=>`${(pad+(i/(values.length-1||1))*(w-pad*2)).toFixed(1)},${(h-pad-((v-min)/(max-min))*(h-pad*2)).toFixed(1)}`).join(' ');return `<div class="chart-wrap"><svg viewBox="0 0 ${w} ${h}"><polyline points="${pts}" class="chart-line"/></svg></div>`}
function renderPlayerProfile(){const box=document.getElementById('playerProfile');if(!box)return;const p=getPlayer(selectedProfileId);if(!p){box.innerHTML='<div class="notice">Spilleren findes ikke.</div>';return}const winrate=p.games?Math.round(p.wins/p.games*100):0,diff=p.matchPointsFor-p.matchPointsAgainst,groups=getTournamentGroups(p),recent=[...p.results].sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,12);box.innerHTML=`<div class="profile-header"><div><div class="profile-kicker">Spillerprofil</div><h2>${escapeHtml(p.name)}</h2><div class="profile-rating">${p.ratingPoints} ratingpoint</div></div></div><div class="profile-stats"><div class="profile-stat"><strong>${p.games}</strong>Kampe</div><div class="profile-stat"><strong>${p.wins}</strong>Sejre</div><div class="profile-stat"><strong>${p.losses}</strong>Nederlag</div><div class="profile-stat"><strong>${winrate}%</strong>Winrate</div><div class="profile-stat"><strong>${p.matchPointsFor}</strong>Point for</div><div class="profile-stat"><strong>${formatSigned(diff)}</strong>Pointdiff.</div></div><div class="profile-section"><h3>Ratingudvikling</h3>${buildRatingChart(p)}</div><div class="profile-section"><h3>Rediger spiller</h3><input id="profileNameInput" value="${escapeHtml(p.name)}"><button onclick="editPlayerName()">Gem nyt navn</button><button class="red" onclick="deletePlayer('${p.id}',event)">Slet spiller permanent</button></div><div class="profile-section"><h3>Seneste kampe</h3>${recent.length?recent.map(renderProfileResult).join(''):'<div class="empty-state">Ingen kampe endnu.</div>'}</div>`}
function renderProfileResult(r){return `<div class="result-row"><div class="result-icon ${r.result==='W'?'win':'loss'}">${r.result==='W'?'V':'T'}</div><div><strong>${r.scoreFor}-${r.scoreAgainst}</strong><div class="muted">${formatDate(r.date)} · Runde ${r.round} · Bane ${r.court}</div></div><div class="result-rating ${r.ratingChange>0?'positive':'negative'}">${formatSigned(r.ratingChange)}</div></div>`}

function renderSquad(){const list=document.getElementById('squadList'),q=(document.getElementById('searchPlayer')?.value||'').trim().toLowerCase();list.innerHTML='';squad.slice().sort((a,b)=>a.name.localeCompare(b.name,'da')).filter(p=>p.name.toLowerCase().includes(q)).forEach(p=>{const active=tonightIds.includes(p.id),reserve=reserveIds.includes(p.id),diff=p.matchPointsFor-p.matchPointsAgainst,el=document.createElement('div');el.className='player-card '+(active?'selected':reserve?'reserve-selected':'');el.onclick=()=>cyclePlayerStatus(p.id);el.innerHTML=`<div class="check">${active?'✓':reserve?'R':''}</div><div><div class="name">${escapeHtml(p.name)}</div><div class="muted">${p.games} kampe · ${p.wins} sejre · ${p.losses} nederlag</div><div class="score-line">${p.matchPointsFor}-${p.matchPointsAgainst} · diff ${formatSigned(diff)}</div></div><div class="player-actions"><div class="points">${p.ratingPoints}</div><button class="profile-player" onclick="openPlayerProfile('${p.id}',event,'squadView')">Profil</button><button class="delete-player" onclick="deletePlayer('${p.id}',event)">🗑️</button></div>`;list.appendChild(el)});document.getElementById('selectedCount').textContent=`Aktive: ${tonightIds.length} / ${participantTarget}`;document.getElementById('reserveCount').textContent=`Reserver: ${reserveIds.length}`}
function renderMatches(){const box=document.getElementById('matches'),sel=document.getElementById('roundSelector');box.innerHTML='';sel.innerHTML='';document.getElementById('matchTitle').textContent=currentRound?'Kampe · runde '+displayedRound:'Kampe';if(!rounds.length){box.innerHTML='<div class="panel"><p class="sub">Ingen kampe endnu.</p></div>';renderMatchStatus(null);return}rounds.forEach(r=>{const b=document.createElement('button');b.textContent='Runde '+r.roundNumber;b.className=r.roundNumber===displayedRound?'':'inactive';b.onclick=()=>{displayedRound=r.roundNumber;saveState();renderMatches()};sel.appendChild(b)});let r=getDisplayedRoundData()||getCurrentRoundData();if(!r)return;renderMatchStatus(r);r.matches.forEach(m=>{const a1=getPlayer(m.teamA[0]),a2=getPlayer(m.teamA[1]),b1=getPlayer(m.teamB[0]),b2=getPlayer(m.teamB[1]);if(!a1||!a2||!b1||!b2)return;const aw=m.saved&&m.scoreA>m.scoreB,bw=m.saved&&m.scoreB>m.scoreA,card=document.createElement('article');card.className='court-card';card.innerHTML=`<div class="court-header"><div class="court-title">Bane ${m.court}</div><div class="court-state ${m.saved?'saved':''}">${m.saved?'✓ Gemt':'Mangler resultat'}</div></div><div class="team ${aw?'winner':''}">${renderTeamPlayer(a1,m.rankA[0])}${renderTeamPlayer(a2,m.rankA[1])}</div><div class="vs">MOD</div><div class="team ${bw?'winner':''}">${renderTeamPlayer(b1,m.rankB[0])}${renderTeamPlayer(b2,m.rankB[1])}</div>${m.saved?`<div class="saved-result">${m.scoreA}-${m.scoreB}</div>${m.round===currentRound?`<button class="secondary" onclick="editMatch('${m.id}')">Ret resultat</button>`:''}`:`<div class="score-grid"><div class="score-field"><label>Par 1</label><input id="scoreA-${m.id}" type="number" min="0" inputmode="numeric"></div><div class="score-field"><label>Par 2</label><input id="scoreB-${m.id}" type="number" min="0" inputmode="numeric"></div></div><button onclick="saveMatch('${m.id}')">Gem bane ${m.court}</button>`}`;box.appendChild(card)})}
function renderTeamPlayer(p,rank){const s=getTonightStats(p);return `<div class="team-player"><div><strong>${escapeHtml(p.name)}</strong><span class="muted"> · nr. ${rank}</span></div><div class="team-player-score">${p.ratingPoints} · ${s.matchPointsFor}-${s.matchPointsAgainst}</div></div>`}
function renderLeaderboard(){const box=document.getElementById('leaderboard');box.innerHTML='';if(tonightIds.length!==participantTarget){box.innerHTML='<div class="notice">Turneringen er ikke klar.</div>';return}getLeaderboard().forEach((p,i)=>{const s=getTonightStats(p),el=document.createElement('div');el.className='leader-card clickable';el.onclick=()=>openPlayerProfile(p.id,null,'leaderView');el.innerHTML=`<div class="place">${i<3?['🥇','🥈','🥉'][i]:i+1}</div><div><div class="name">${escapeHtml(p.name)}</div><div class="muted">${s.wins} sejre · ${s.losses} nederlag</div><div class="score-line">Kampscore ${s.matchPointsFor}-${s.matchPointsAgainst}</div></div><div class="points">${p.ratingPoints}</div>`;box.appendChild(el)})}
function renderHistory(){const box=document.getElementById('tournamentHistory');if(!box)return;box.innerHTML=tournamentHistory.length?tournamentHistory.map(t=>`<div class="history-card"><div><strong>${formatDate(t.date)}</strong><div class="muted">${t.players} spillere · ${t.courts} baner · ${t.roundCount} runder</div><div class="score-line">Vinder: ${escapeHtml(t.winner)}</div></div><button class="secondary history-toggle" onclick="toggleHistory('${t.id}')">Slutstilling</button><div id="history-${t.id}" class="history-detail hidden">${t.finalBoard.map(p=>`<div class="history-row"><span>${p.place}. ${escapeHtml(p.name)}</span><strong>${p.ratingPoints}</strong></div>`).join('')}</div></div>`).join(''):'<div class="empty-state">Ingen afsluttede turneringer endnu.</div>'}
function toggleHistory(id){document.getElementById('history-'+id)?.classList.toggle('hidden')}
function renderSubstitutionPanel(){const panel=document.getElementById('substitutionPanel'),out=document.getElementById('outPlayerSelect'),inside=document.getElementById('inPlayerSelect');if(!panel||!out||!inside)return;panel.classList.toggle('hidden',!tournamentId||!reserveIds.length);out.innerHTML='<option value="">Vælg spiller</option>'+tonightIds.map(id=>`<option value="${id}">${escapeHtml(getPlayer(id)?.name||'')}</option>`).join('');inside.innerHTML='<option value="">Vælg reserve</option>'+reserveIds.map(id=>`<option value="${id}">${escapeHtml(getPlayer(id)?.name||'')}</option>`).join('')}
function renderStatus(){const courts=getCourtCount(),r=getCurrentRoundData(),saved=r?r.matches.filter(m=>m.saved).length:0;document.getElementById('statSquad').textContent=squad.length;document.getElementById('statTonight').textContent=`${tonightIds.length}/${participantTarget}`;document.getElementById('statRound').textContent=`${currentRound}/${totalRounds}`;document.getElementById('statResults').textContent=`${saved}/${courts}`;document.getElementById('participantTarget').value=participantTarget;document.getElementById('totalRoundsInput').value=totalRounds;document.getElementById('courtCountText').textContent=`${participantTarget} spillere = ${courts} baner`;document.querySelectorAll('.status-grid').forEach(el=>el.style.gridTemplateColumns=`repeat(${courts},1fr)`);renderHomeStatus(r);const n=document.getElementById('homeNotice');if(tonightIds.length!==participantTarget)n.textContent=`Vælg ${participantTarget} aktive spillere.`;else if(!currentRound)n.textContent=`Klar: ${participantTarget} spillere, ${courts} baner og ${totalRounds} runder.`;else if(currentRound===totalRounds&&allMatchesSaved(r))n.textContent='Turneringen er afsluttet og gemt.';else if(allMatchesSaved(r))n.textContent='Runden er færdig. Lav næste runde.';else n.textContent=`Runde ${currentRound} er i gang.`;document.getElementById('topStatus').textContent=`${tonightIds.length} aktive · ${reserveIds.length} reserver · Runde ${currentRound}/${totalRounds}`;renderSubstitutionPanel()}
function buildStatusBoxes(r){return Array.from({length:getCourtCount()},(_,i)=>i+1).map(c=>{const m=r?.matches.find(x=>x.court===c);return `<div class="status-box ${!m?'':m.saved?'done':'missing'}">B${c}<br>${!m?'–':m.saved?'✓':'!'}</div>`}).join('')}
function renderHomeStatus(r){document.getElementById('roundStatus').innerHTML=buildStatusBoxes(r)}function renderMatchStatus(r){document.getElementById('matchStatus').innerHTML=buildStatusBoxes(r)}

function seedExampleSquad(){['Thomas','Peter','Martin','Søren','Lars','Jens','Kasper','Anders','Mads','Rasmus','Michael','Henrik','Jesper','Niels','Christian','Jonas','Bo','Claus','Mikkel','Frederik','Simon','Mathias','Kim','Jan','Carsten','Emil','Oliver','Nicklas','Brian','Daniel'].forEach(name=>{if(!squad.some(p=>p.name.toLowerCase()===name.toLowerCase()))squad.push(createPlayer(name))});saveState();updateUI();showView('squadView')}
function resetTonight(){if(!confirm('Nulstil turneringen? Aftenens resultater trækkes tilbage.'))return;rounds.forEach(r=>r.matches.forEach(m=>{if(m.applied)rollbackMatchResult(m)}));tonightIds=[];reserveIds=[];tournamentId=null;currentRound=0;displayedRound=0;rounds=[];saveState();updateUI();showView('squadView')}
function resetEverything(){if(!confirm('Slet hele bruttotruppen og al historik?'))return;squad=[];tonightIds=[];reserveIds=[];tournamentId=null;currentRound=0;displayedRound=0;rounds=[];participantTarget=20;totalRounds=4;tournamentHistory=[];localStorage.removeItem(STORAGE_KEY);localStorage.removeItem(LEGACY_KEY);updateUI();showView('homeView')}
function exportData(){const json=JSON.stringify({version:7,exportedAt:new Date().toISOString(),squad,tonightIds,reserveIds,tournamentId,currentRound,displayedRound,rounds,participantTarget,totalRounds,tournamentHistory},null,2);navigator.clipboard?.writeText(json).then(()=>alert('Sikkerhedskopien er kopieret.')).catch(()=>prompt('Kopiér:',json))||prompt('Kopiér:',json)}
function importData(){const json=prompt('Indsæt sikkerhedskopien:');if(!json)return;try{const d=JSON.parse(json);if(!Array.isArray(d.squad))throw new Error();if(!confirm('Erstat nuværende data?'))return;squad=d.squad||[];tonightIds=d.tonightIds||[];reserveIds=d.reserveIds||[];tournamentId=d.tournamentId||null;currentRound=d.currentRound||0;displayedRound=d.displayedRound||currentRound;rounds=d.rounds||[];participantTarget=d.participantTarget||20;totalRounds=d.totalRounds||4;tournamentHistory=d.tournamentHistory||[];migratePlayers();cleanInvalidReferences();saveState();updateUI()}catch{alert('Sikkerhedskopien kunne ikke læses.')}}
function showView(id){['homeView','squadView','matchesView','leaderView','profileView','historyView','adminView'].forEach(v=>{document.getElementById(v).classList.add('hidden');document.getElementById('tab-'+v)?.classList.remove('active')});document.getElementById(id).classList.remove('hidden');document.getElementById('tab-'+id)?.classList.add('active');if(id==='matchesView'&&currentRound&&!displayedRound)displayedRound=currentRound;updateUI();window.scrollTo({top:0,behavior:'smooth'})}
function updateUI(){renderSquad();renderMatches();renderLeaderboard();renderHistory();renderStatus();if(selectedProfileId)renderPlayerProfile()}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify({squad,tonightIds,reserveIds,tournamentId,currentRound,displayedRound,rounds,participantTarget,totalRounds,tournamentHistory}))}
function loadState(){const saved=localStorage.getItem(STORAGE_KEY)||localStorage.getItem(LEGACY_KEY);if(!saved)return;try{const d=JSON.parse(saved);squad=d.squad||[];tonightIds=d.tonightIds||[];reserveIds=d.reserveIds||[];tournamentId=d.tournamentId||null;currentRound=d.currentRound||0;displayedRound=d.displayedRound||currentRound;rounds=d.rounds||[];participantTarget=d.participantTarget||20;totalRounds=d.totalRounds||4;tournamentHistory=d.tournamentHistory||[]}catch{}}
function formatSigned(n){return n>0?'+'+n:String(n)}function formatDate(v){try{return new Intl.DateTimeFormat('da-DK',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(v))}catch{return v||'-'}}function escapeHtml(v){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
init();